package com.lth.ecommerceagent.tenant;
import java.util.*; import java.util.regex.Pattern;
import com.lth.ecommerceagent.user.*;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/organization")
public class OrganizationController{
 private final CompanyRepository companies; private final StoreRepository stores; private final CompanyMemberRepository companyMembers; private final StoreMemberRepository storeMembers; private final StoreMemberPermissionRepository permissionRepo; private final UserRepository users; private final PasswordEncoder encoder; private final StorePlatformConfigRepository storePlatformConfigs;
 public OrganizationController(CompanyRepository c,StoreRepository s,CompanyMemberRepository cm,StoreMemberRepository sm,StoreMemberPermissionRepository p,UserRepository u,PasswordEncoder e,StorePlatformConfigRepository spc){companies=c;stores=s;companyMembers=cm;storeMembers=sm;permissionRepo=p;users=u;encoder=e;storePlatformConfigs=spc;}
 public record CompanyRequest(String name,Long ownerUserId,String ownerEmail,String ownerPassword,String ownerDisplayName){} public record StoreRequest(String name){}
 public record AvailableUser(Long id,String email){}
 public record MemberRequest(String email,String displayName,String password,List<Long> storeIds,Set<Permission> permissions){} public record PermissionRequest(Set<Permission> permissions){}
 public record MemberView(Long id,Long userId,String email,Long storeId,String storeName,String status,Set<Permission> permissions){}
 public record CompanyDetail(Company company,List<Store> stores,List<MemberView> members,List<MemberView> owners){}
 @GetMapping("/companies") public List<Company> companies(){var p=TenantContext.principal();if(p!=null&&p.isSuperAdmin())return companies.findAll().stream().filter(c->!"DELETED".equals(c.getStatus())).toList();return p==null?List.of():List.of(companies.findById(p.companyId()).orElseThrow());}
 @PutMapping("/companies/{id}/status") @PreAuthorize("hasRole('SUPER_ADMIN')") public Company updateCompanyStatus(@PathVariable Long id,@RequestBody Map<String,String> body){var c=companies.findById(id).orElseThrow();if("DISABLED".equalsIgnoreCase(body.getOrDefault("status","ACTIVE"))){c.setStatus("DISABLED");}else{c.setStatus("ACTIVE");}return companies.save(c);}
 @DeleteMapping("/companies/{id}") @PreAuthorize("hasRole('SUPER_ADMIN')") public void deleteCompany(@PathVariable Long id){var c=companies.findById(id).orElseThrow();if(!stores.findByCompanyIdAndStatusOrderByCreatedAt(id,"ACTIVE").isEmpty())throw conflict("该企业已有店铺，只能停用，不能删除");c.setStatus("DELETED");companies.save(c);}
 @DeleteMapping("/stores/{id}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','OWNER')") public void deleteStore(@PathVariable Long id){var p=TenantContext.principal();var s=stores.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"店铺不存在"));if(p==null||(!p.isSuperAdmin()&&!p.companyId().equals(s.getCompanyId())))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"无权删除该店铺");for(var sm:storeMembers.findByStoreId(id))permissionRepo.deleteByStoreMemberId(sm.getId());storeMembers.deleteByStoreId(id);storePlatformConfigs.deleteByStoreId(id);stores.delete(s);}
 @GetMapping("/companies/{id}/detail") public CompanyDetail detail(@PathVariable Long id){var p=TenantContext.principal();if(p==null||(!p.isSuperAdmin()&&!id.equals(p.companyId())))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"无权查看该企业");var c=companies.findById(id).orElseThrow();var ss=stores.findByCompanyIdAndStatusOrderByCreatedAt(id,"ACTIVE");var ms=storeMembers.findByCompanyIdAndStatus(id,"ACTIVE").stream().map(this::view).toList();var os=companyMembers.findByCompanyIdAndStatus(id,"ACTIVE").stream().map(this::ownerView).toList();return new CompanyDetail(c,ss,ms,os);}
 @GetMapping("/available-users") @PreAuthorize("hasRole('SUPER_ADMIN')") public List<AvailableUser> availableUsers(){return users.findAll().stream().filter(u->!"SUPER_ADMIN".equals(u.getRole())).filter(u->companyMembers.findByUserIdAndStatus(u.getId(),"ACTIVE").isEmpty()).map(u->new AvailableUser(u.getId(),u.getEmail())).toList();}
 @PostMapping("/companies") @PreAuthorize("hasRole('SUPER_ADMIN')") public Company createCompany(@RequestBody CompanyRequest r){
  if(blank(r.name()))throw bad("企业名称不能为空"); User u;
  if(r.ownerUserId()!=null) u=users.findById(r.ownerUserId()).orElseThrow(()->bad("老板用户不存在"));
  else { if(blank(r.ownerEmail())||blank(r.ownerPassword()))throw bad("请填写企业老板邮箱和初始密码"); String email=r.ownerEmail().trim().toLowerCase(); if(users.findByEmail(email).isPresent())throw conflict("老板邮箱已存在，请选择已有用户"); u=new User(email,encoder.encode(r.ownerPassword()),"USER"); u.setDisplayName(r.ownerDisplayName()); u=users.save(u); }
  if("SUPER_ADMIN".equals(u.getRole()))throw bad("超级管理员不能作为企业老板"); if(!companyMembers.findByUserIdAndStatus(u.getId(),"ACTIVE").isEmpty())throw conflict("该用户已经属于企业");
  Company c=new Company();c.setName(r.name().trim());c=companies.save(c);CompanyMember cm=new CompanyMember();cm.setCompanyId(c.getId());cm.setUserId(u.getId());cm.setRole(MemberRole.OWNER);companyMembers.save(cm);return c;
 }
 @GetMapping("/stores") public List<Store> stores(){var p=TenantContext.principal();if(p==null||p.companyId()==null)return List.of();if(p.memberRole()==MemberRole.OWNER)return stores.findByCompanyIdAndStatusOrderByCreatedAt(p.companyId(),"ACTIVE");return storeMembers.findByUserIdAndStatus(p.userId(),"ACTIVE").stream().map(x->stores.findByIdAndCompanyIdAndStatus(x.getStoreId(),p.companyId(),"ACTIVE").orElse(null)).filter(Objects::nonNull).toList();}
 @PostMapping("/stores") @PreAuthorize("hasRole('OWNER')") public Store createStore(@RequestBody StoreRequest r){if(blank(r.name()))throw bad("店铺名称不能为空");var p=TenantContext.principal();Store s=new Store();s.setCompanyId(p.companyId());s.setName(r.name().trim());s.setCode("STORE-"+java.util.UUID.randomUUID().toString().replace("-","").substring(0,12).toUpperCase());return stores.save(s);}
 @GetMapping("/permissions") public List<String> permissionList(){return Arrays.stream(Permission.values()).map(Enum::name).toList();}
 @GetMapping("/members") @PreAuthorize("hasAuthority('PERM_MEMBER_MANAGE')") public List<MemberView> members(){var p=TenantContext.principal();return storeMembers.findByCompanyIdAndStatus(p.companyId(),"ACTIVE").stream().map(this::view).toList();}
 @PostMapping("/members") @PreAuthorize("hasAuthority('PERM_MEMBER_MANAGE')") public List<MemberView> addMember(@RequestBody MemberRequest r){if(r.email()==null||!Pattern.compile("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$").matcher(r.email().trim()).matches())throw bad("请输入有效邮箱");var p=TenantContext.principal();String email=r.email().trim().toLowerCase();User u=users.findByEmail(email).orElse(null);if(u==null){String password=blank(r.password())?"123457":r.password();if(password.length()<6)throw bad("新账号密码至少6位");u=new User(email,encoder.encode(password),"USER");u.setDisplayName(r.displayName());u=users.save(u);}if(r.storeIds()==null||r.storeIds().isEmpty())throw bad("至少选择一个店铺");List<MemberView> out=new ArrayList<>();for(Long storeId:r.storeIds()){stores.findByIdAndCompanyIdAndStatus(storeId,p.companyId(),"ACTIVE").orElseThrow(()->bad("店铺不存在或不属于当前企业"));var sm=storeMembers.findByStoreIdAndUserIdAndStatus(storeId,u.getId(),"ACTIVE").orElse(null);if(sm==null){sm=new StoreMember();sm.setCompanyId(p.companyId());sm.setStoreId(storeId);sm.setUserId(u.getId());sm=storeMembers.save(sm);}savePermissions(sm.getId(),r.permissions());out.add(view(sm));}return out;}
 @PutMapping("/members/{id}/permissions") @PreAuthorize("hasRole('OWNER') or hasAuthority('PERM_MEMBER_MANAGE')") @org.springframework.transaction.annotation.Transactional public MemberView updatePermissions(@PathVariable Long id,@RequestBody PermissionRequest r){var sm=member(id);permissionRepo.deleteByStoreMemberId(id);savePermissions(id,r.permissions());return view(sm);}
 @PutMapping("/members/{id}/status") @PreAuthorize("hasAuthority('PERM_MEMBER_MANAGE')") public MemberView updateStatus(@PathVariable Long id,@RequestBody Map<String,String> r){var sm=member(id);if(sm.getUserId().equals(TenantContext.userId()))throw conflict("不能修改当前登录成员状态");sm.setStatus(r.getOrDefault("status","ACTIVE"));return view(storeMembers.save(sm));}
 private StoreMember member(Long id){var p=TenantContext.principal();return storeMembers.findById(id).filter(x->x.getCompanyId().equals(p.companyId())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private void savePermissions(Long id,Set<Permission> ps){if(ps!=null)permissionRepo.saveAll(ps.stream().map(x->new StoreMemberPermission(id,x)).toList());}
 private MemberView view(StoreMember m){Store s=stores.findById(m.getStoreId()).orElseThrow();User u=users.findById(m.getUserId()).orElseThrow();return new MemberView(m.getId(),u.getId(),u.getEmail(),s.getId(),s.getName(),m.getStatus(),permissionRepo.findByStoreMemberId(m.getId()).stream().map(StoreMemberPermission::getPermission).collect(java.util.stream.Collectors.toSet()));}
 private MemberView ownerView(CompanyMember m){User u=users.findById(m.getUserId()).orElseThrow();return new MemberView(m.getId(),u.getId(),u.getEmail(),null,"企业",m.getStatus(),java.util.Set.of());}
 private boolean blank(String s){return s==null||s.isBlank();}private ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private ResponseStatusException conflict(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}
}
