package com.lth.ecommerceagent.tenant;

public enum Permission {
    PRODUCT_VIEW, PRODUCT_CREATE, PRODUCT_EDIT, CONTENT_GENERATE, CONTENT_EXECUTE, CONTENT_REVIEW, CONTENT_PUBLISH,
    ORDER_VIEW, ORDER_CREATE, ORDER_REVIEW, ORDER_SHIP, INVENTORY_VIEW, INVENTORY_CREATE, INVENTORY_ADJUST,
    PURCHASE_CREATE, PURCHASE_APPROVE, PURCHASE_RECEIVE, SUPPLIER_MANAGE,
    PLATFORM_CONFIG, PLATFORM_ORDER_SYNC, PLATFORM_PUBLISH, MEMBER_MANAGE, STORE_MANAGE, AUDIT_VIEW
}
